### ISSUE TITLE
Can I use this adapter in serverless edge environment such as Cloudflare Workers or Vercel Functions

### ISSUE THREAD

**Issue by m430** [tidbcloud/prisma-adapter#21]
https://github.com/prisma/prisma/issues/21394#issuecomment-1992311887

I noticed the prisma has been released a preview version with edge environment, I want to use tidb serverless with prisma.

**Comment by zhangyangyu** [comment]
Hi @m430 , we've just released the corresponding version `5.11.0`. With this version, you can use this adapter against TiDB Serverless with Prisma on edge envs like Vercel and Cloudflare Workers. You can refer this repo https://github.com/tidbcloud/serverless-driver-example for samples.
