### ISSUE TITLE
Doesn't work with latest prisma

### ISSUE THREAD

**Issue by rverma-dev** [tidbcloud/prisma-adapter#23]
Give validation error for driverName not mapped

**Comment by shiyuhang0** [comment]
Hi, could you provide the Prisma version, adapter version, and serverless-js version?
I can not reproduce with the following version:
1. Prisma: v5.1.4

**Comment by rverma-dev** [comment]
Its the adapter version which is culprit, if you simply bump the adapter version to 5.14.0 you can also see  the issue in adapter code.
<img width="973" alt="adapter" src="https://github.com/tidbcloud/prisma-adapter/assets/80032502/836090e5-7652-4208-973a-6202a69b8c19">

**Comment by shiyuhang0** [comment]
The adapter doesn't release v5.14.0. Here is the list of releases https://github.com/tidbcloud/prisma-adapter/releases

**Comment by rverma-dev** [comment]
We need to bump up https://www.npmjs.com/package/@prisma/driver-adapter-utils

**Comment by shiyuhang0** [comment]
We have released a series of versions according to the Prisma version, you can take one as you need.
It should resolve your issue, could you have a try?

**Comment by shiyuhang0** [comment]
i will close it as it is inactivity. Feel free to reopen it if you have any questions
